homepage/urls.py
from django.urls import path
from . import views

app_name = 'homepage'

urlpatterns = [
    path('', views.home1, name='home1'),
    path('about/', views.about, name='about'),
    path('education/', views.education, name='education'),
    path('experience/', views.experience, name='experience'),
    path('schedule/', views.jadwal, name='jadwal'),
    path('schedule_create/', views.schedule_create, name='schedule_create'),
    path('schedule_delete/', views.schedule_delete, name='schedule_delete'),
]

story4/urls.py
from django.urls import path, include
from django.contrib import admin


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls', namespace='homepage')),
]

homepage/models.py
from django.db import models
from datetime import datetime

class Jadwal (models.Model):

    hari = models.CharField(max_length = 10)
    tanggal = models.DateField()
    jam = models.TimeField()
    kegiatan  = models.CharField(max_length = 100)
    tempat = models.CharField(max_length = 100)
    kategori = models.CharField(max_length = 60)


    def __str__(self):
        return self.kegiatan

homepage/forms.py
from django import forms
from .models import Jadwal

class JadwalForm(forms.ModelForm):

    kegiatan = forms.CharField(widget=forms.TextInput(attrs={
        "class" : "form-control",
        "placeholder" : "Nama Kegiatan",
    }))
    hari = forms.CharField(widget=forms.TextInput(attrs={
        "class" : "form-control",
        "placeholder" : "Hari",
    }))
    tanggal = forms.DateField(widget=forms.DateInput(attrs={
        "class" : "form-control",
        "placeholder" : "(YYYY-MM-DD)"
    }))
    jam = forms.TimeField(widget=forms.TimeInput(attrs={
        "class" : "form-control",
        "placeholder" : "(JAM:MENIT:DETIK)"
    }))
    tempat = forms.CharField(widget=forms.TextInput(attrs={
        "class" : "form-control",
        "placeholder" : "Nama Tempat",
    }))
    kategori = forms.CharField(widget=forms.TextInput(attrs={
        "class" : "form-control",
        "placeholder" : "Kategori",
    }))

    class Meta:
        model = Jadwal
        fields = ['kegiatan', 'tanggal', 'jam', 'tempat', 'kategori', 'hari']
        

homepage/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import Jadwal
from . import forms
 

# Create your views here.
def home1(request):
    return render(request, 'home1.html')

def about(request):
    return render(request, 'about.html')

def education(request):
    return render(request, 'education.html')

def experience(request):
    return render(request, 'experience.html')

def jadwal(request):
    jadwals = Jadwal.objects.order_by('tanggal')
    return render(request, 'schedule.html', {'jadwals': jadwals})

def schedule_create(request):
    if request.method == 'POST':
        form = forms.JadwalForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('homepage:jadwal')

    form = forms.JadwalForm()
    return render(request, 'schedule_create.html', {'form': form})

def schedule_delete(request):
	jadwal = Jadwal.objects.all().delete()
	return render(request, 'schedule.html')

homepage/templates/about.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Rani Aprilia</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- <link rel="stylesheet" type="text/css" media="screen" href="s.css"> -->
    <script src="main.js"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    
    <link href="https://fonts.googleapis.com/css?family=Kurale|Laila|Shrikhand&display=swap" rel="stylesheet">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

</head>
<body class="about" style= "position : fixed">
    
    <nav class="navbar navbar-expand-lg navbar-light bg-light nav-home">
        <a class="navbar-brand"></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse " id="navbarNavAltMarkup">
          <div class="navbutton navbar-nav">
            <a class="nav-item nav-link active" href="{% url 'homepage:home1' %}">Home <span class="sr-only">(current)</span></a>
            <a class="nav-item nav-link" href="{% url 'homepage:about' %}">About</a>
            <a class="nav-item nav-link" href="{% url 'homepage:education' %}">Education</a>
            <a class="nav-item nav-link" href="{% url 'homepage:experience' %}">Experience</a>
            <a class="nav-item nav-link" href="{% url 'homepage:jadwal' %}">Schedule</a>
          </div>
        </div>
      </nav>

    <div class="container">
        <div class="row row-desc">
            <div class="col-md-4 col-12">
                <img class="DP" src="{% static 'images/DP2.png'%}" alt="dp">
            </div>
            <div class="col-md-8 col-12 col-desc">
                <p class="name">Hello, <br>my name is Rani Aprilia Astrianty</p>
                <p class="desc">I am 19 years old. I am currently studying as a second-year 
                        <br>student at the Faculty of Computer Science, majoring in 
                        <br>Information System at Universitas Indonesia.
                        <br>I’am a very responsible, thorough, and sociable person. 
                        <br>I love to draw, dance, and recently have interest in 
                        <br>photography.
                </p>
            </div>
        </div>
        <div class="row row-contact">
            <div class="col-3 col-contact">
                <a href='https://www.instagram.com/raniapriliaa/'><img id="ig" src="{% static 'images/ins.png'%}"> <br> raniapriliaa</a>
            </div>
            <div class="col-3 col-contact">
                <a href='https://twitter.com/raniiapriliaa'><img id = "twt" src="{% static 'images/twt.png'%}"><br> raniiapriliaa</a>
            </div>
            <div class="col-3 col-contact">
                <a href='mailto:rani.apriliaa@gmail.com'><img id = "mail" src="{% static 'images/mail.png' %}"><br> rani.apriliaa@gmail.com</a>
            </div>
            <div class="col-3 col-contact">
                <a href='https://line.me/en/'><img id = "line" src="{% static 'images/line.png' %}"><br> raniiapriliaa</a>
            </div>
        </div>
    </div>
</body>  
    
</html>
            
            
            
            
            
            

homepage/templates/education.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Rani Aprilia</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- <link rel="stylesheet" type="text/css" media="screen" href="main.css"> -->
    <script src="main.js"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Kurale|Laila|Shrikhand&display=swap" rel="stylesheet">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>


</head>
<body class="background3">
    
    <nav class="navbar navbar-expand-lg navbar-light bg-light nav-home">
        <a class="navbar-brand"></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse " id="navbarNavAltMarkup">
          <div class="navbutton navbar-nav">
            <a class="nav-item nav-link active" href="{% url 'homepage:home1' %}">Home <span class="sr-only">(current)</span></a>
            <a class="nav-item nav-link" href="{% url 'homepage:about' %}">About</a>
            <a class="nav-item nav-link" href="{% url 'homepage:education' %}">Education</a>
            <a class="nav-item nav-link" href="{% url 'homepage:experience' %}">Experience</a>
            <a class="nav-item nav-link" href="{% url 'homepage:jadwal' %}">Schedule</a>
          </div>
        </div>
      </nav>
    <div class="education text-center">Education</div>

    <div class = "container">
        <div class = "row row-contact">
            <div class = "col-md-6 ">
            </div>

            <div class = "col-md-2 col-sm-12 coll ">
                <img class="sdlogo" src="{% static 'images/sd.png'%}" alt="sd">
                
            </div>
            <div class="col-md-4 col-sm-12">
                <p class = "sd">Azhari Islamic School Cilandak
                <br>2006-2012</p>
            </div>
        </div>
       
        <div class = "row row-contact">
            <div class = "col-md-6 ">
            </div>
            <div class = "col-md-2 col-sm-12 coll ">
                <img class="smplogo" src="{% static 'images/smp.png'%}" alt="smp">
            </div>
            <div class="col-md-4 col-sm-12">
                <p class="smp">SMPN 218 Jakarta
                    <br>2012-2015
            </div>
        </div>

        <div class="row row-contact"> 
            <div class="col-md-6 "></div>
            <div class="col-md-2 col-sm-12 coll ">
                <img class = "smalogo" src="{% static 'images/sma.png'%}"alt="sma">
            </div>
            <div class="col-md-4 col-sm-12">
                <p class="sma">SMAN 28 Jakarta
                    <br>2015-2018</p>
            </div>
        </div>

        <div class="row row-contact"> 
            <div class="col-md-6 "></div>
            <div class="col-md-2 col-sm-12 coll ">
                <img class = "univlogo" src="{% static 'images/ui.png'%}"alt="ui">
            </div>
            <div class="col-md-4 col-sm-12 ">
                <p class="univ">Faculty of Computer
                    <br>Science, University of
                    <br>Indonesia
                    <br>2018 - present</p>
            </div>
        </div>
        

    </div>
                

</body>
    

homepage/templates/experience.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Rani Aprilia</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" media="screen" href="main.css">
    <script src="main.js"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Kurale|Laila|Shrikhand&display=swap" rel="stylesheet">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>


</head>
<body class="background4" no-repeat;>
    
    <nav class="navbar navbar-expand-lg navbar-light bg-light nav-home">
        <a class="navbar-brand"></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse " id="navbarNavAltMarkup">
          <div class="navbutton navbar-nav">
            <a class="nav-item nav-link active" href="{% url 'homepage:home1' %}">Home <span class="sr-only">(current)</span></a>
            <a class="nav-item nav-link" href="{% url 'homepage:about' %}">About</a>
            <a class="nav-item nav-link" href="{% url 'homepage:education' %}">Education</a>
            <a class="nav-item nav-link" href="{% url 'homepage:experience' %}">Experience</a>
            <a class="nav-item nav-link" href="{% url 'homepage:jadwal' %}">Schedule</a>
          </div>
        </div>
      </nav>
    <div class="experience text-center">Experience</div>

    
        <div class="row row-exp row1">
            <div class="col-md-3 col-sm-6 cc">
                <img class="exp1" src="{% static 'images/exp1.png'%}" alt="exp1">
            </div>
            <div class="col-md-3 col-sm-6 cc">
                <img class="exp2" src="{% static 'images/exp2.png'%}" alt="exp2">
            </div>
            <div class="col-md-3 col-sm-6 cc">
                <img class="exp3" src="{% static 'images/exp3.png'%}" alt="exp3">
            </div>
            <div class="col-md-3 col-sm-6 cc">
                <img class="exp4" src="{% static 'images/exp4.png'%}" alt="exp4">
            </div>
        </div>

        

        <div class="row row-exp row1 ">
                <div class="col-md-3 col-sm-6 cc">
                    <img class="exp5" src="{% static 'images/exp5.png'%}" alt="exp5">
                </div>
                <div class="col-md-3 col-sm-6 cc">
                    <img class="exp6" src="{% static 'images/exp6.png'%}" alt="exp6">
                </div>
                <div class="col-md-3 col-sm-6 cc">
                    <img class="exp7" src="{% static 'images/exp7.png'%}" alt="exp7">
                </div>
                <div class="col-md-3 col-sm-6 cc">
                    <img class="exp8" src="{% static 'images/exp8.png'%}" alt="exp8">
                </div>
    
        </div>
        <div class="row row-exp row1">
                <div class="col-md-12 col-sm-12 cc">
                    <img class="qq" src="{% static 'images/quote.png'%}" alt="quote">
                </div>
        </div>


    

homepage/templates/home1.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Rani Aprilia</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script src="main.js"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    
    <link href="https://fonts.googleapis.com/css?family=Kurale|Laila|Shrikhand&display=swap" rel="stylesheet">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static './css/style.css' %}">

</head>
<body class="home">
    

    <nav class="navbar navbar-expand-lg navbar-light bg-light nav-home">
        <a class="navbar-brand"></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse " id="navbarNavAltMarkup">
          <div class="navbutton navbar-nav">
            <a class="nav-item nav-link active" href="{% url 'homepage:home1' %}">Home <span class="sr-only">(current)</span></a>
            <a class="nav-item nav-link" href="{% url 'homepage:about' %}">About</a>
            <a class="nav-item nav-link" href="{% url 'homepage:education' %}">Education</a>
            <a class="nav-item nav-link" href="{% url 'homepage:experience' %}">Experience</a>
            <a class="nav-item nav-link" href="{% url 'homepage:jadwal' %}">Schedule</a>
          </div>
        </div>
      </nav>

    

    <div class="container">
        
        <div class="row rowhome1">
            <div class="col-md-12 col-sm-12 col1">
                <p class="title text-center">Welcome to My Site!</p>
            </div>
        </div>
        <div class= "row rowhome2">
            <div class="col col2">
                <img src="{% static 'images/avatar1.png'%}" class="img-fluid" alt="ava">  
            </div>
        </div>
        <div class = "row rowhome3">
            <div class="col-md-3 col-sm-3 ">

            </div>
            <div class= "col-md-3 col-sm-3 col3">
                <p class="startBtn"><a href="{% url 'homepage:about' %}">Click Here</a></p>
            </div>
            <div class="col-md-3 col-sm-3">

            </div>
        </div>
    </div>
</body>
</html>

homepage/templates/schedule.html
{% load static %}
{% block content %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Rani Aprilia</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script src="main.js"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Kurale|Laila|Shrikhand&display=swap" rel="stylesheet">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
</head>

<body class="about" style= "position : fixed">
    
    <nav class="navbar navbar-expand-lg navbar-light bg-light nav-home">
        <a class="navbar-brand"></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse " id="navbarNavAltMarkup">
          <div class="navbutton navbar-nav">
            <a class="nav-item nav-link active" href="{% url 'homepage:home1' %}">Home <span class="sr-only">(current)</span></a>
            <a class="nav-item nav-link" href="{% url 'homepage:about' %}">About</a>
            <a class="nav-item nav-link" href="{% url 'homepage:education' %}">Education</a>
            <a class="nav-item nav-link" href="{% url 'homepage:experience' %}">Experience</a>
            <a class="nav-item nav-link" href="{% url 'homepage:jadwal' %}">Schedule</a>
          </div>
        </div>
      </nav>

      <!-- test -->
      <h1 class="schedule">Schedule</h1>
      <div class="article">
          <a href="{% url 'homepage:jadwal' %}"></a>
          <div class="article">
              <div class="row">
                  {% for jadwal in jadwals %}
                      <div class="col-sm-4 text-center">
                          <h2>{{ jadwal.kegiatan }}</h2>
                          <p>{{ jadwal.tanggal }}</p>
                          <p>{{ jadwal.jam}}</p>
                          <p>{{ jadwal.tempat }}</p>
                          <p>{{ jadwal.kategori }}</p>
                      </div>
                  {% endfor %}
              </div>
          </div>
      </div>
      <div class = 'col-md-12'>
            <div class = 'form-group'>
                    <a href="{% url 'homepage:schedule_create' %}"><button type="button" class= "btn btn-secondary btn-lg btn-sm">Create</button></a>
                    <a href="{% url 'homepage:schedule_delete' %}"><button type="button" class= "btn btn-secondary btn-lg btn-sm">Clear</button></a>
                    
        
      </div>
  </div>
  
  {% endblock %}
  
</body>
</html>

homepage/templates/schedule_create.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Rani Aprilia</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script src="main.js"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Kurale|Laila|Shrikhand&display=swap" rel="stylesheet">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

</head>
<body class="about" style= "position : fixed">
    
    <nav class="navbar navbar-expand-lg navbar-light bg-light nav-home">
        <a class="navbar-brand"></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse " id="navbarNavAltMarkup">
          <div class="navbutton navbar-nav">
            <a class="nav-item nav-link active" href="{% url 'homepage:home1' %}">Home <span class="sr-only">(current)</span></a>
            <a class="nav-item nav-link" href="{% url 'homepage:about' %}">About</a>
            <a class="nav-item nav-link" href="{% url 'homepage:education' %}">Education</a>
            <a class="nav-item nav-link" href="{% url 'homepage:experience' %}">Experience</a>
            <a class="nav-item nav-link" href="{% url 'homepage:jadwal' %}">Schedule</a>
          </div>
        </div>
      </nav>

      <form class="css" action="{% url 'homepage:schedule_create' %}" method="post">
          {% csrf_token %}
          <div class="form-row">
              <div class="col-sm-1"></div>
              <div class="form-group col-sm-10">
                  {% for fields in form %}
                      {{ fields.label_tag }}
                      <br>
                      {{ fields }}
                  {% endfor %}
              </div>
          </div>
          <div class="form-row">
              <div class="col-sm-1"></div>
              <input type="submit" class="btn btn-primary float-right text" value="Add">
          </form>
  
</body>
</html>